thymeleaf:
  cache: false
  prefix: file:src/main/resources/templates/
  view-names: thymeleaf/*
  suffix: .html
  check-template-location: true
code:
  secret: ${random.value}
  bignumber: ${random.long}
  uuid: ${random.uuid}
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/kitchen?serverTimezone=UTC
    username: kitchen_dba
    password: 1234
    initialization-mode: always
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
devtools:
  restart:
    enabled: true
  livereload:
    enabled: true
  thymeleaf:
    cache: sfalse
logging:
  level:
    org:
      hibernate:
        type: trace